
{
    "name": "Planetio",
    "version": "14.0.1.0.0",
    'author': "Alessandro Vasi / Roberto Zanardo / Encodata S.r.l.",
    'summary': 'Modulo per la compilazione della due-diligence sulla normativa della deforestazione',
    'depends': [
        'base',
        'mail',
        'web'
        ],
    "data": [
        "security/ir.model.access.csv",
        "views/eudr/eudr_views.xml",
        "views/eudr/eudr_views_inh.xml",
        'views/data_import/job_views.xml',
        "views/data_import/template_views.xml",
        "views/wizard_views.xml",
        "views/wizard_views_inh.xml",
        'views/questionnaire/planetio_question_views.xml',
        'views/questionnaire/public_questionnaire_template.xml',
        'views/questionnaire/public_questionnaire_success.xml',
        'views/questionnaire/public_questionnaire_error.xml',
        'views/res_config_settings_inh.xml',
        'views/otp_verification_wizard.xml',
        'reports/report_dds.xml',
        'reports/report_dds_template.xml',
        'data/planetio_eudr_params.xml',
        'data/template_seed.xml',
        'data/p2p_tracer_params.xml',
        'data/sequence.xml',
    ],
    "installable": True,
    "application": True,
}
